apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: rogeroliveira
spec:
  type: NodePort
  selector:
    app: rogeroliveira-playlist-recommender
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 50026
